### PR TITLE
Title font size

### PR DESCRIPTION
**Pull request by kernesti**
Hi

I added possibility to add font size for the chart title. I found it useful and hopefully someone else does too.

### CODE REVIEW

**Comment by kernesti** [comment]
Added line width to scatter series

**Comment by kernesti** [comment]
Added few other useful things

**Comment by JonathanTron** [comment]
Hi, thanks for taking the time to participate in this project.

What's the use case for serializing in reverse? 
Why not introduce this logic in your code generating the worksheets?

**Comment by kernesti** [comment]
Hi,

I'm generating worksheets in opposite order as I would like them to appear in the output file. Some of the worksheets have to be created last, such as a summary, but they should appear first in the file.

**Comment by kernesti** [comment]
Hi, sorry for not replying for a long time. I have checked how Excel creates the xml data with nil values and they are not written, so I was trying to replicate that. I'm not sure if it actually affects the end result, it does not affect how the charts are rendered though.

**Comment by JonathanTron** [comment]
Thanks for checking it out.

**Pull request merged**
